name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create distribution
      run: ./prepare-distribution.sh
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Desktop Commander CLI Release
          
          ## Installation
          
          ### Quick Install (macOS/Linux)
          ```bash
          curl -fsSL https://github.com/${{ github.repository_owner }}/desktop-commander/releases/latest/download/install.sh | bash
          ```
          
          ### Manual Installation
          1. Download `desktop-commander-cli.zip` from the assets below
          2. Extract and run `./install.sh` (macOS/Linux) or `install.bat` (Windows)
          
          ## What's New
          - See [CHANGELOG.md](https://github.com/${{ github.repository_owner }}/desktop-commander/blob/main/CHANGELOG.md)
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/desktop-commander-cli.zip
        asset_name: desktop-commander-cli.zip
        asset_content_type: application/zip
    
    - name: Upload Install Script
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./install.sh
        asset_name: install.sh
        asset_content_type: text/plain